Add Windows Support
Bricklou/grindstone-rs pull request #1
Opened 2022-10-14 21:43 UTC by Superloup10

2022-10-14 21:47 UTC, Bricklou requested changes

2022-10-14 21:47 UTC, Bricklou commented on src/minecraft/java/search_jre.rs
> +            .join("Microsoft.4297127D64EC6_8wekyb3d8bbwe") // TODO: Find a way to get the package name
Move this key to a constant

2022-10-14 21:47 UTC, Bricklou commented on src/minecraft/java/search_jre.rs
> +        //unimplemented!("Not now, i need to setup a rust dev environment on one of my computers.");
don't forget to remove this line

2022-10-18 07:05 UTC, Bricklou commented on src/constants.rs
> +pub const MC_MS_STORE_IDENTIFIANT: &str = "Microsoft.4297127D64EC6_8wekyb3d8bbwe";
In English ?

2022-10-18 07:05 UTC, Bricklou commented on src/minecraft/java/download_file.rs
> +                    std::fs::remove_file(&path)?; // TODO Warning: Unnecessary qualification
What does "unnecessary qualification" stand for ?

2022-10-18 13:44 UTC, Superloup10 commented on src/minecraft/java/download_file.rs
> +                    std::fs::remove_file(&path)?; // TODO Warning: Unnecessary qualification
It's `std::` which is not needed, `fs` is imported at the top of the file.

2022-10-18 13:47 UTC, Superloup10 commented on src/constants.rs
> +pub const MC_MS_STORE_IDENTIFIANT: &str = "Microsoft.4297127D64EC6_8wekyb3d8bbwe";
My bad, `identifiant` sounded English to me.

2022-10-18 15:20 UTC, Bricklou approved these changes

2022-10-19 16:48 UTC, merged